iversion: 2
jobs:
 build:
   machine: true
   working_directory: /tmp

   steps:
     - checkout
     - run: docker-compose -f docker-compose-dev.yml up --build -d
     - run: docker-compose exec users python manage.py test
